version: '3.9'

services:
  dev-db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    networks:
      - networkName
networks:
  networkName:
